import Head from "next/head";
import ProductsComponent from "./ProductsComponent";
import SliderComponent from "./SliderComponent";

const HomeComponent = () => {
  return (
    <div className="">
      <Head>
        <title>@SSR App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SliderComponent />

      <ProductsComponent />
    </div>
  );
};

export default HomeComponent;
