import Head from "next/head";
import SliderComponent from "./SliderComponent";

const HomeComponent = () => {
  return (
    <div className="">
      <Head>
        <title>@SSR App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <SliderComponent />



    </div>
  );
};

export default HomeComponent;
